# Generated by Django 6.0.3 on 2026-03-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khach', models.CharField(max_length=100, verbose_name='Tên khách hàng')),
                ('toa_do_x', models.FloatField(verbose_name='Tọa độ X')),
                ('toa_do_y', models.FloatField(verbose_name='Tọa độ Y')),
                ('bat_dau', models.IntegerField(default=8, verbose_name='Giờ sớm nhất')),
                ('ket_thuc', models.IntegerField(default=18, verbose_name='Giờ muộn nhất')),
                ('trang_thai', models.CharField(choices=[('CHUA_GIAO', 'Chưa giao'), ('DANG_GIAO', 'Đang giao'), ('DA_GIAO', 'Đã giao')], default='CHUA_GIAO', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Danh sách Đơn hàng',
            },
        ),
    ]
