# Generated by Django 6.0.3 on 2026-03-22 02:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donhang',
            options={'ordering': ['-ngay_tao'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Danh sách Đơn hàng'},
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='bat_dau',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='ket_thuc',
        ),
        migrations.AddField(
            model_name='donhang',
            name='dia_chi',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='khung_gio_muon',
            field=models.IntegerField(default=18, verbose_name='Giờ muộn nhất (0-24)'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='khung_gio_som',
            field=models.IntegerField(default=8, verbose_name='Giờ sớm nhất (0-24)'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='ma_don',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã đơn hàng'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donhang',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
        migrations.AddField(
            model_name='donhang',
            name='thoi_gian_phuc_vu',
            field=models.IntegerField(default=10, verbose_name='TG phục vụ (phút)'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='toa_do_x',
            field=models.FloatField(default=0.0, verbose_name='Tọa độ X (Kinh độ)'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='toa_do_y',
            field=models.FloatField(default=0.0, verbose_name='Tọa độ Y (Vĩ độ)'),
        ),
    ]
